"use client";
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from "boneyard-js";

import _product_card from "./product-card.bones.json";

registerBones({
  "product-card": _product_card,
});
